# Generated by Django 4.2.29 on 2026-03-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.PositiveIntegerField(default=50, verbose_name='装甲 (HP)')),
                ('success', models.PositiveIntegerField(default=60, verbose_name='成功 (Hit Rate)')),
                ('power', models.PositiveIntegerField(default=40, verbose_name='威力 (Power)')),
                ('charge', models.PositiveIntegerField(default=50, verbose_name='充填 (Charge Speed)')),
                ('cooldown', models.PositiveIntegerField(default=50, verbose_name='放熱 (Cooldown Speed)')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性一覧',
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='メダル名')),
                ('personality', models.CharField(choices=[('LEADER', 'リーダー狙い (Attack Leader)'), ('WEAK', '弱者狙い (Attack Weakest)'), ('RANDOM', 'ランダム (Attack Random)'), ('STRONG', '強者狙い (Attack Strongest)')], default='RANDOM', max_length=8, verbose_name='性格')),
                ('skill_head', models.PositiveSmallIntegerField(default=5, verbose_name='頭部熟練度')),
                ('skill_ra', models.PositiveSmallIntegerField(default=5, verbose_name='右腕熟練度')),
                ('skill_la', models.PositiveSmallIntegerField(default=5, verbose_name='左腕熟練度')),
                ('skill_leg', models.PositiveSmallIntegerField(default=5, verbose_name='脚部熟練度')),
            ],
            options={
                'verbose_name': 'メダル',
                'verbose_name_plural': 'メダル一覧',
            },
        ),
        migrations.CreateModel(
            name='Medarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='機体名')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medarots', to='battle.medal', verbose_name='メダル')),
            ],
            options={
                'verbose_name': 'メダロット',
                'verbose_name_plural': 'メダロット一覧',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='チーム名')),
                ('leader_index', models.PositiveSmallIntegerField(default=0, verbose_name='リーダー番号 (0/1/2)')),
                ('medarot_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_1', to='battle.medarot', verbose_name='1番機')),
                ('medarot_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_2', to='battle.medarot', verbose_name='2番機')),
                ('medarot_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_3', to='battle.medarot', verbose_name='3番機')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム一覧',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='部品名')),
                ('system', models.CharField(choices=[('HEAD', '頭部 (Head)'), ('RA', '右腕 (Right Arm)'), ('LA', '左腕 (Left Arm)'), ('LEG', '脚部 (Leg)')], default='HEAD', max_length=4, verbose_name='系統')),
                ('skill_kind', models.CharField(choices=[('SHOOT', '射撃 (Shoot)'), ('MELEE', '格闘 (Melee)'), ('GUARD', '守る (Guard)'), ('HEAL', '治す (Heal)'), ('SUPPORT', '補助 (Support)'), ('NONE', 'なし (None)')], default='NONE', max_length=8, verbose_name='スキル種別')),
                ('special_effect', models.CharField(choices=[('PIERCE', '貫通 (Pierce)'), ('DOT', '継続ダメージ (Damage over Time)'), ('REFLECT', '反射 (Reflect)'), ('NONE', 'なし (None)')], default='NONE', max_length=8, verbose_name='特殊効果')),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='battle.attribute', verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '部品',
                'verbose_name_plural': '部品一覧',
            },
        ),
        migrations.AddField(
            model_name='medarot',
            name='part_head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medarot_head', to='battle.part', verbose_name='頭部パーツ'),
        ),
        migrations.AddField(
            model_name='medarot',
            name='part_la',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medarot_la', to='battle.part', verbose_name='左腕パーツ'),
        ),
        migrations.AddField(
            model_name='medarot',
            name='part_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medarot_leg', to='battle.part', verbose_name='脚部パーツ'),
        ),
        migrations.AddField(
            model_name='medarot',
            name='part_ra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medarot_ra', to='battle.part', verbose_name='右腕パーツ'),
        ),
        migrations.CreateModel(
            name='BattleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_json', models.TextField(default='{}', verbose_name='バトル状態 (JSON)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='終了フラグ')),
                ('winner', models.CharField(blank=True, choices=[('A', 'チームA'), ('B', 'チームB'), ('', '未決定')], default='', max_length=1, verbose_name='勝者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_a', to='battle.team', verbose_name='チームA')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_b', to='battle.team', verbose_name='チームB')),
            ],
            options={
                'verbose_name': 'バトルセッション',
                'verbose_name_plural': 'バトルセッション一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
